name: 'Pages Zola'
author: 'Zakhary Kaplan'
description: >-
  A simple GitHub Action for producing Zola build artifacts compatible with
  GitHub Pages
inputs:
  source:
    description: 'Directory where the source files reside.'
    required: false
    default: ./
  destination:
    description: >-
      Output directory of the build. Although it can be nested inside the
      source, it cannot be the same as the source directory.
    required: false
    default: ./public
runs:
  using: 'docker'
  image: 'Dockerfile'
